# Generated by Django 5.2.5 on 2025-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание",
                max_length=250,
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
