# Generated by Django 5.2.5 on 2025-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="name",
            field=models.CharField(
                help_text="Укажите вариант ответа", verbose_name="Вариант ответа"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(help_text="Укажите вопрос", verbose_name="Вопрос"),
        ),
    ]
