# Generated by Django 5.2.5 on 2025-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_choice_name_alter_question_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.CharField(
                default=1,
                help_text="Укажите варианты ответа",
                verbose_name="Варианты ответа",
            ),
            preserve_default=False,
        ),
    ]
