# Generated by Django 5.2.5 on 2025-09-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_section_description"),
        ("tests", "0003_question_correct_answer_question_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="section",
            field=models.ForeignKey(
                help_text="Выберите раздел",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="learning.section",
                verbose_name="Раздел",
            ),
        ),
    ]
