# Generated by Django 5.2.5 on 2025-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_alter_test_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="selected_choice",
            field=models.CharField(),
        ),
    ]
