# Generated by Django 5.2.5 on 2025-09-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_alter_answer_selected_choice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
